name: scheduled-job

on:
  workflow_dispatch: 
  schedule:
    - cron: "40 13 * * *"
    - cron: "40 7 * * *"


jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print formatted time
        run: date +"%Y-%m-%d %H:%M:%S"

