name: scheduled-job

on:
  schedule:
    - cron: "55 12 * * *"


jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print formatted time
        run: date +"%Y-%m-%d %H:%M:%S"

